### ISSUE TITLE
Request: Run command on power on

### ISSUE THREAD

**Issue by wormiedk** [kantlivelong/OctoPrint-PSUControl#125] opened 2019-04-02 12:40 UTC
I have a printer with 2208 steppers which need to be initialized every time the printer has been off. It would be great if I could have PSUcontrol insert one or more g-codes when the PSU is turned on

**Comment by kantlivelong** [comment] 2019-04-10 00:59
Duplicate of #64

**Closed by kantlivelong** 2019-04-10 00:59 UTC
