### ISSUE TITLE
[Minor Bug] The "Switching method" is always showing the "G-Code Command" when returning to the settings page

### ISSUE THREAD

**Issue by leoheck** [kantlivelong/OctoPrint-PSUControl#138] opened 2019-08-16 01:42 UTC
![image](https://user-images.githubusercontent.com/1277920/63137551-1db29100-bfad-11e9-89a5-3bac227cde3a.png)

I set the "Switching method" to "GPIO pin", it is working fine. But when I go back to the PSU Control config page, it shows the default "G-Code Command". In other words, it is not saving the state of this field.

#### What did you expect to happen?
To see the "Switching method" to "GPIO pin" as it was set.

#### What happened instead?
It is displaying the same "G-Code Command" string. The behavior is OK, the issue is only the string that is not being stored.

#### Version of OctoPrint-PSUControl
0.1.8

#### Operating System running OctoPrint
RaspiberryPi 3
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

#### Printer model & used firmware incl. version
Ender 3

**Comment by chriswal** [comment] 2019-08-22 02:14
when i try to set gpio it works on my system. octoprint 1.3.11 and psucontrol 0.1.8.
i use a system command for switching --so i didnt start from gcode.
try to set a system command before and look if its saved. then the try the gpio again.

**Comment by TazerReloaded** [comment] 2020-06-17 08:31
Still having this bug in 0.8.9. Steps to reproduce:
- set to "GPIO pin"
- save settings
- reload page
- open settings, it now says "System command" again, sometimes just one option, sometimes both

**Comment by leoheck** [comment] 2020-06-17 14:06
I agree, there is something strange with this page it does not load the right settings when coming back to the page.

**Comment by ccanevit** [comment] 2020-09-16 15:52
I'm experiencing this issue as well, PSU Control (0.1.9), OctoPrint Version 1.4.2. I set this to GPIO pin, and it keeps reverting to G-CODE. Although it works when I manually press the PSU control from OctoPrint, it won't turn the PSU on on startup of the server.

This causes an issue, since my printer (Ender 3 v2) will not accept any G-Code commands unless I power it via usb or have the PSU on.

**Comment by kantlivelong** [comment] 2020-12-16 17:43
This should be fixed in 0.1.10

**Closed** 2021-03-09 21:34 UTC
Labels: confirmed bug, solved
